### ISSUE TITLE
Extension doesn't activate

### ISSUE THREAD

**Issue by adalisk-emikhaylov** [zokugun/vscode-explicit-folding#52]
## Describe the issue
Extension no longer works.

I'm not entirely sure, but I *think* this only happens on Windows on my work machine, and it works on Ubuntu on my home machine.

I tried to reinstall the extension, it didn't help. I also tried to delete `C:\Users\emikhaylov\.vscode\extensions\zokugun.explicit-folding-...` before installing again, and nothing changed.

In `Output -> Log (Extension Host)` there's following:
```
[2021-06-25 16:34:20.245] [exthost] [error] Activating extension zokugun.explicit-folding failed due to an error:
[2021-06-25 16:34:20.245] [exthost] [error] Error: Cannot find module 'c:\Users\emikhaylov\.vscode\extensions\zokugun.explicit-folding-0.14.5\out\extension'
Require stack:
- c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
	at Module._load (internal/modules/cjs/loader.js:779:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
	at Function.n._load (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:27815)
	at Function.E._load (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:24567)
	at Function.c._load (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:59196)
	at Module.require (internal/modules/cjs/loader.js:1006:19)
	at require (internal/modules/cjs/helpers.js:88:18)
	at Function.t [as __$__nodeRequire] (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:101)
	at m._loadCommonJSModule (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:25973)
	at m._doActivateExtension (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12617)
	at m._activateExtension (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11676)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)
	at async m.$activate (c:\Users\emikhaylov\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:20167)
```

In `C:\Users\emikhaylov\.vscode\extensions\zokugun.explicit-folding-0.14.5` I see following files:
`CHANGELOG.md  icon.png  LICENSE.txt  package.json  README.md`

## To reproduce

- VSCode: 1.57.1
- Explicit Folding: 0.14.5
- Language: `cpp` (probably doesn't matter?)

## Expected behavior
Extension activates.

**Comment by daiyam** [comment]
Shit! I'm using Github Actions to publish the extension. It seems there is a serious issue with the action (updated yesterday).
I've just manually published the extension so it should be available soon.
